import Head from "next/head"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
import "../firebase"
import { useEffect, useState } from "react"
import { app } from "../firebase"
import { getMessaging, getToken } from "firebase/messaging"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  const [deviceId, setDeviceId] = useState("")

  useEffect(() => {
    const messaging = getMessaging(app)
    getToken(messaging, {
      vapidKey: "BPU0IGD8azFPNNwycLDe_TYruIFMYKpxD_k0KBEsiHC7Bp-g5Md2jmu3lBXL6SbCXkv8gAKatu9F8sSagOEZ1Ik",
    })
      .then(currentToken => {
        if (currentToken) {
          setDeviceId(currentToken)
          console.log("Token: ", currentToken)
        } else {
          console.log("No registration token available. Request permission to generate one.")
        }
      })
      .catch(err => {
        console.log("An error occurred while retrieving token. ", err)
      })
  })

  return (
    <>
      <Head>
        <title> ID</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p className={inter.className}>
          <h1>Device ID:</h1>
          <p>{deviceId}</p>
        </p>
      </main>
    </>
  )
}
